---
# Ansible playbook for a LAMP server.

- hosts: apache
  gather_facts: yes
  tasks:
  - name: install apache
    apt: name=apache2 update_cache=yes state=latest
  - name: install php
    apt: name=php5 state=present
  - name: install mysql
    apt: name=mysql-server state=present